apiVersion: apps/v1
kind: Deployment
metadata:
  name: aswcloud-k8s-deployment
  labels:
    app: aswcloud-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aswcloud-k8s
  template:
    metadata:
      labels:
        app: aswcloud-k8s
    spec:
      serviceAccountName: aswcloud-k8s-sa
      containers:
        - name: server
          image: aoikazto/k8s-server:0.1.7
          ports:
            - containerPort: 8000
        - env:
            - name: LOCALHOST
              value: false
