apiVersion: apps/v1
kind: Deployment
metadata:
  name: aswcloud-comm-deployment
  labels:
    app: aswcloud-comm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aswcloud-comm
  template:
    metadata:
      labels:
        app: aswcloud-comm
    spec:
      containers:
        - name: server
          image: aoikazto/aswcloud-server:1.1.12
          ports:
            - containerPort: 8088
          env:
            - name: MONGODB_SERVER
              value: aswcloud-comm-database-service.aswcloud.svc.cluster.local
            - name: MONGODB_PORT
              value: '27017'
            - name: MONGODB_DATABASE
              value: servercomm
            - name: JWT_SECRET_TOKEN
              value: test
            - name: MONGODB_ID
              value: root
            - name: MONGODB_PW
              value: example
            - name: KUBERNETES_SERVER
              value: aswcloud-k8s-service.aswcloud.svc.cluster.local:8000
            - name: JWT_SECRET_KEY
              value: EtAp8jnvSkFuwcVuEjZPIGiNBGydsaYM0mFiTi0bLCQq1ekyJGPGTygp41mdtwbleCVhExIOfJZ5rAVXvKlvNadw6EBOuIy2gbxFGV3AW3BcWAtjmD1qvyHvNRZp0j9D
            - name: ADMIN_ID
              value: aoikazto
            - name: ADMIN_PASSWORD
              value: aswcloud_aoikazto
