apiVersion: v1
kind: Service
metadata:
  name: aswcloud-comm-service
spec:
  type: NodePort
  selector:
    app: aswcloud-comm
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30500
      name: "grpc"